# -*- coding: utf-8 -*-
"""CSE423 Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15AVvKB3M_Pxhu7lyf7bPDwP07-Y1fqmL
"""

#MD HASIB ULLAH KHAN ALVIE
#22101371
#ASSIGNMENT1
#CSE423
#SEC10

# ============================================================================
# TASK 1: Task 1: Building a House in Rainfall
# ============================================================================

from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
import random
import math
import time

# Task 1 Global Variables
sky_brightness = 1.0
rain_drops = []
rain_angle = 0.0

class Raindrop:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.speed = random.uniform(8, 12)
        self.length = random.uniform(10, 15)

    def update(self, angle):
        rad = math.radians(angle)
        self.x += math.sin(rad) * self.speed
        self.y -= math.cos(rad) * self.speed

        if self.y < -150:
            self.y = random.uniform(750, 1050)
            self.x = random.uniform(-600, 1500)

        if angle < 0:
            if self.x < -700:
                self.x = random.uniform(1400, 1600)
                self.y = random.uniform(-100, 900)
        else:
            if self.x > 1600:
                self.x = random.uniform(-700, -500)
                self.y = random.uniform(-100, 900)

def init_rain():
    """Initialize rain drops - spawn from ALL SIDES for angled rain"""
    global rain_drops
    rain_drops = []
    for _ in range(1000):
        x = random.uniform(-600, 1500)
        y = random.uniform(-100, 1000)
        rain_drops.append(Raindrop(x, y))

def draw_line(x1, y1, x2, y2):
    """Helper to draw a line"""
    glBegin(GL_LINES)
    glVertex2f(x1, y1)
    glVertex2f(x2, y2)
    glEnd()

def draw_triangle_filled(x1, y1, x2, y2, x3, y3):
    """Helper to draw filled triangle"""
    glBegin(GL_TRIANGLES)
    glVertex2f(x1, y1)
    glVertex2f(x2, y2)
    glVertex2f(x3, y3)
    glEnd()

def draw_sky():
    global sky_brightness
    day_r, day_g, day_b = 0.53, 0.81, 0.92
    night_r, night_g, night_b = 0.05, 0.05, 0.15

    sky_r = night_r + (day_r - night_r) * sky_brightness
    sky_g = night_g + (day_g - night_g) * sky_brightness
    sky_b = night_b + (day_b - night_b) * sky_brightness

    glClearColor(sky_r, sky_g, sky_b, 1.0)

def draw_ground():
    glColor3f(0.13, 0.55, 0.13)

    draw_triangle_filled(0, 0, 900, 0, 900, 120)
    draw_triangle_filled(0, 0, 900, 120, 0, 120)

    glColor3f(0.0, 0.4, 0.0)
    glLineWidth(1)
    for i in range(0, 900, 15):
        x = i + random.uniform(-3, 3)
        draw_line(x, 120, x, 125)


def draw_tree(x, y, size=1.0):
    glColor3f(0.4, 0.26, 0.13)
    trunk_w = 8 * size
    trunk_h = 40 * size
    draw_triangle_filled(x - trunk_w, y, x + trunk_w, y, x + trunk_w, y + trunk_h)
    draw_triangle_filled(x - trunk_w, y, x + trunk_w, y + trunk_h, x - trunk_w, y + trunk_h)

    glColor3f(0.13, 0.7, 0.13)
    leaf_y = y + trunk_h

    draw_triangle_filled(x - 25*size, leaf_y, x, leaf_y + 35*size, x + 25*size, leaf_y)

    draw_triangle_filled(x - 20*size, leaf_y + 20*size, x, leaf_y + 50*size, x + 20*size, leaf_y + 20*size)

    draw_triangle_filled(x - 15*size, leaf_y + 35*size, x, leaf_y + 60*size, x + 15*size, leaf_y + 35*size)

def draw_house():
    global sky_brightness
    #foundation
    glColor3f(0.3, 0.3, 0.3)
    draw_triangle_filled(290, 120, 610, 120, 610, 155)
    draw_triangle_filled(290, 120, 610, 155, 290, 155)
    glColor3f(0.15, 0.15, 0.15)
    glLineWidth(2)
    draw_line(290, 120, 610, 120)
    draw_line(290, 120, 290, 155)
    draw_line(610, 120, 610, 155)
    draw_line(290, 155, 610, 155)
    #housebody
    glColor3f(0.72, 0.45, 0.20)

    draw_triangle_filled(300, 150, 600, 150, 600, 400)
    draw_triangle_filled(300, 150, 600, 400, 300, 400)

    glColor3f(0.25, 0.15, 0.05)
    glLineWidth(3)
    draw_line(300, 150, 600, 150)
    draw_line(300, 150, 300, 400)
    draw_line(600, 150, 600, 400)
    draw_line(300, 400, 600, 400)
    #roof
    glColor3f(0.55, 0.15, 0.15)
    draw_triangle_filled(280, 400, 450, 520, 620, 400)
    glColor3f(0.2, 0.05, 0.05)
    glLineWidth(3)
    draw_line(280, 400, 450, 520)
    draw_line(450, 520, 620, 400)
    #door
    glColor3f(0.3, 0.15, 0.05)
    draw_triangle_filled(410, 150, 490, 150, 490, 280)
    draw_triangle_filled(410, 150, 490, 280, 410, 280)
    glColor3f(0.15, 0.08, 0.02)
    glLineWidth(2)
    draw_line(410, 150, 410, 280)
    draw_line(490, 150, 490, 280)
    draw_line(410, 280, 490, 280)

    # door knob
    glColor3f(0.85, 0.65, 0.13)
    glPointSize(6)
    glBegin(GL_POINTS)
    glVertex2f(470, 215)
    glEnd()

    #window
    glColor3f(0.95, 0.87, 0.51)  # Warm yellow light (CONSTANT)
    # left window
    draw_triangle_filled(320, 260, 370, 260, 370, 340)
    draw_triangle_filled(320, 260, 370, 340, 320, 340)
    # right window
    draw_triangle_filled(530, 260, 580, 260, 580, 340)
    draw_triangle_filled(530, 260, 580, 340, 530, 340)
    glColor3f(0.95, 0.95, 0.9)
    glLineWidth(3)

    draw_line(320, 260, 370, 260)
    draw_line(320, 260, 320, 340)
    draw_line(370, 260, 370, 340)
    draw_line(320, 340, 370, 340)
    draw_line(345, 260, 345, 340)
    draw_line(320, 300, 370, 300)

    draw_line(530, 260, 580, 260)
    draw_line(530, 260, 530, 340)
    draw_line(580, 260, 580, 340)
    draw_line(530, 340, 580, 340)
    draw_line(555, 260, 555, 340)
    draw_line(530, 300, 580, 300)
def draw_rain():
    global rain_drops, rain_angle, sky_brightness
    # rain color based on time
    if sky_brightness > 0.5:
        glColor3f(0.7, 0.8, 0.95)
    else:
        glColor3f(0.8, 0.85, 0.95)
    glLineWidth(2)
    rad = math.radians(rain_angle)
    for drop in rain_drops:
        dx = math.sin(rad) * drop.length
        dy = math.cos(rad) * drop.length
        draw_line(drop.x, drop.y, drop.x + dx, drop.y - dy)
def task1_display():
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    glLoadIdentity()
    draw_sky()
    draw_ground()
    draw_tree(150, 120, 0.8)
    draw_tree(220, 120, 1.0)
    draw_house()
    draw_tree(750, 120, 1.0)
    draw_tree(820, 120, 0.7)
    draw_rain()
    glutSwapBuffers()

def task1_animate():
    global rain_drops, rain_angle
    for drop in rain_drops:
        drop.update(rain_angle)
    time.sleep(0.016)
    glutPostRedisplay()

def task1_keyboard(key, x, y):
    global sky_brightness
    if key == b'd' or key == b'D':
        sky_brightness = min(1.0, sky_brightness + 0.1)
        print(f"☀️ DAY... Sky Brightness: {sky_brightness:.1f}")
    elif key == b'n' or key == b'N':
        sky_brightness = max(0.0, sky_brightness - 0.1)
        print(f"🌙 NIGHT... Sky Brightness: {sky_brightness:.1f}")
    glutPostRedisplay()

def task1_special_keys(key, x, y):
    global rain_angle, sky_brightness

    if key == GLUT_KEY_UP:
        sky_brightness = 1.0
        rain_angle = 0.0
        print("☀️ DAY mode + Rain straight")
    elif key == GLUT_KEY_DOWN:
        sky_brightness = 0.0  #
        rain_angle = 0.0
        print("🌙 NIGHT mode + Rain straight")
    elif key == GLUT_KEY_LEFT:
        rain_angle = max(-45, rain_angle - 5)
        print(f"🌧️ Rain angle: {rain_angle}° (LEFT)")
    elif key == GLUT_KEY_RIGHT:
        rain_angle = min(45, rain_angle + 5)
        print(f"🌧️ Rain angle: {rain_angle}° (RIGHT)")

    glutPostRedisplay()

def task1_init():
    global rain_drops
    glViewport(0, 0, 900, 700)
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    glOrtho(0, 900, 0, 700, -1, 1)
    glMatrixMode(GL_MODELVIEW)
    glLoadIdentity()
    init_rain()

def run_task1():
    glutInit()
    glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE | GLUT_DEPTH)
    glutInitWindowSize(900, 700)
    glutInitWindowPosition(100, 50)
    glutCreateWindow(b"Task 1: Premium Rainy House Scene")
    task1_init()
    glutDisplayFunc(task1_display)
    glutIdleFunc(task1_animate)
    glutKeyboardFunc(task1_keyboard)
    glutSpecialFunc(task1_special_keys)
    print("\n" + "="*70)
    print("TASK 1: PREMIUM RAINY HOUSE SCENE (Realistic Physics)")
    print("="*70)
    print("🏠 Features:")
    print("  - Premium brick house with chimney")
    print("  - Grass field with trees")
    print("  - Realistic rain (doesn't go through house!)")
    print("  - Smooth 60 FPS animation")
    print("  - Only sky color changes (house stays same)")
    print("\n⌨️  Controls:")
    print("  D/d         - Gradually brighten sky (toward day)")
    print("  N/n         - Gradually darken sky (toward night)")
    print("  UP Arrow    - Instant day + reset rain angle")
    print("  DOWN Arrow  - Instant night + reset rain angle")
    print("  LEFT Arrow  - Tilt rain LEFT (wind from left)")
    print("  RIGHT Arrow - Tilt rain RIGHT (wind from right)")
    print("="*70 + "\n")

    glutMainLoop()


# ============================================================================
# TASK 2: Building the Amazing Box
# ============================================================================

WIDTH, HEIGHT = 700, 600
current_width, current_height = WIDTH, HEIGHT
point_speed = 2.0
is_frozen = False
is_blinking_active = False

class MovingPoint:
    """Class representing a moving point"""
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.color = (random.random(), random.random(), random.random())
        self.dir_x = random.choice([-1, 1])
        self.dir_y = random.choice([-1, 1])
        self.show_point = True

    def update(self):
        """Update point position and blinking"""
        global point_speed, is_frozen, is_blinking_active

        #update blinking
        if is_blinking_active:
            elapsed = time.time()
            self.show_point = (int(elapsed * 2) % 2 == 0)
        else:
            self.show_point = True
        #update position
        if not is_frozen:
            self.x += self.dir_x * point_speed
            self.y += self.dir_y * point_speed
            #bounce off walls
            if self.x <= -WIDTH//2 or self.x >= WIDTH//2:
                self.dir_x *= -1
                self.x = max(-WIDTH//2, min(WIDTH//2, self.x))

            if self.y <= -HEIGHT//2 or self.y >= HEIGHT//2:
                self.dir_y *= -1
                self.y = max(-HEIGHT//2, min(HEIGHT//2, self.y))

    def draw(self):
        """Draw the point"""
        if self.show_point:
            glColor3f(self.color[0], self.color[1], self.color[2])
        else:
            glColor3f(0.0, 0.0, 0.0)
        glPointSize(7)
        glBegin(GL_POINTS)
        glVertex2f(self.x, self.y)
        glEnd()

#list to store all points
all_points = []

def draw_boundary_box():
    glColor3f(1.0, 1.0, 1.0)  # White
    glLineWidth(2)

    half_w = WIDTH // 2
    half_h = HEIGHT // 2

    draw_line(-half_w, -half_h, half_w, -half_h)
    draw_line(half_w, -half_h, half_w, half_h)
    draw_line(half_w, half_h, -half_w, half_h)
    draw_line(-half_w, half_h, -half_w, -half_h)

def task2_display():
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    glLoadIdentity()
    draw_boundary_box()
    for point in all_points:
        point.draw()

    glutSwapBuffers()

def task2_animate():
    global all_points
    for point in all_points:
        point.update()

    glutPostRedisplay()


def task2_mouse(button, state, x, y):
    global all_points, is_blinking_active, is_frozen, current_width, current_height

    if is_frozen:
        print("❄️ System is FROZEN! Unfreeze first (press SPACEBAR)")
        return

    if state == GLUT_DOWN:
        norm_x = x / current_width
        norm_y = y / current_height

        gl_x = (norm_x - 0.5) * WIDTH
        gl_y = (0.5 - norm_y) * HEIGHT

        if button == GLUT_RIGHT_BUTTON:
            # right click: create new point
            new_point = MovingPoint(gl_x, gl_y)
            all_points.append(new_point)
            print(f"✨ Point created at ({int(gl_x)}, {int(gl_y)}). Total: {len(all_points)}")

        elif button == GLUT_LEFT_BUTTON:
            # left click: toggle blinking for ALL points (continuous)
            is_blinking_active = not is_blinking_active
            if is_blinking_active:
                print("💫 Blinking STARTED (continuous)")
            else:
                print("💫 Blinking STOPPED (back to normal)")

def task2_keyboard(key, x, y):
    global is_frozen
    if key == b' ':
        is_frozen = not is_frozen
        if is_frozen:
            print("❄️ FROZEN")
        else:
            print("▶️ UNFROZEN")


def task2_special_keys(key, x, y):
    global point_speed, is_frozen

    if is_frozen:
        print("❄️ System is FROZEN! Unfreeze first (press SPACEBAR)")
        return

    if key == GLUT_KEY_UP:
        point_speed = min(10.0, point_speed + 0.5)
        print(f"⬆️ Speed increased: {point_speed:.1f}")
    elif key == GLUT_KEY_DOWN:
        point_speed = max(0.5, point_speed - 0.5)
        print(f"⬇️ Speed decreased: {point_speed:.1f}")

def task2_init():
    glViewport(0, 0, WIDTH, HEIGHT)
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    glOrtho(-WIDTH//2, WIDTH//2, -HEIGHT//2, HEIGHT//2, -1, 1)
    glMatrixMode(GL_MODELVIEW)
    glLoadIdentity()
    glClearColor(0.0, 0.0, 0.0, 1.0)


def run_task2():
    glutInit()
    glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE | GLUT_DEPTH)
    glutInitWindowSize(WIDTH, HEIGHT)
    glutInitWindowPosition(100, 50)
    glutCreateWindow(b"Task 2: Amazing Box")

    task2_init()

    glutDisplayFunc(task2_display)
    glutIdleFunc(task2_animate)
    glutMouseFunc(task2_mouse)
    glutKeyboardFunc(task2_keyboard)
    glutSpecialFunc(task2_special_keys)

    print("\n" + "="*60)
    print("TASK 2: AMAZING BOX WITH MOVING POINTS")
    print("="*60)
    print("Controls:")
    print("  RIGHT CLICK  - Create new moving point at click position")
    print("  LEFT CLICK   - Toggle blinking ON/OFF (continuous)")
    print("  SPACEBAR     - Freeze/Unfreeze (disables ALL functions)")
    print("  UP Arrow     - Increase speed (only when unfrozen)")
    print("  DOWN Arrow   - Decrease speed (only when unfrozen)")
    print("="*60 + "\n")

    glutMainLoop()


# ============================================================================
# MAIN PROGRAM
# ============================================================================

if __name__ == "__main__":
    import sys

    print("\n" + "="*60)
    print("CSE423 - ASSIGNMENT 1")
    print("="*60)
    print("Choose a task to run:")
    print("  1 - Task 1: Premium Rainy House Scene")
    print("  2 - Task 2: Amazing Box with Moving Points")
    print("="*60)

    choice = input("Enter your choice (1 or 2): ").strip()

    if choice == '1':
        run_task1()
    elif choice == '2':
        run_task2()
    else:
        print("Invalid choice! Please run again and enter 1 or 2.")
        sys.exit(1)