# -*- coding: utf-8 -*-
"""22101371_Md Hasib Ullah Khan Alvie_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-FqZnO0-XSz2ktDgjgP8o5p1L-a9U1Qh
"""

from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
import math
import random
import ctypes

# Font setup
GLUT_BITMAP_HELVETICA_18 = ctypes.c_void_p(0x0004)
GLUT_BITMAP_TIMES_ROMAN_24 = ctypes.c_void_p(0x0008)

# World dimensions
WORLD_SIZE = 15
TILE_SIZE = 1.0

# Player state
gun_pos_x = WORLD_SIZE / 2.0
gun_pos_z = WORLD_SIZE / 2.0
gun_rotation = 0.0
remaining_health = 5
total_score = 0
shots_missed_count = 0
is_game_active = True

# Camera configuration
view_angle = 0.0
view_distance = 15.0
view_elevation = 18.0
perspective_mode = "third"  # "third" or "first"

# Cheat features
auto_fire_enabled = False
auto_aim_camera = False
fire_cooldown_timer = 0
current_target_index = 0

# Game objects
enemy_list = []
ENEMY_COUNT = 5
projectile_list = []
PROJECTILE_VELOCITY = 0.15

# Colors
COLOR_PINK = (1.0, 0.8, 0.9)
COLOR_GREEN = (0.8, 1.0, 0.8)


def render_text_overlay(screen_x, screen_y, message, font=GLUT_BITMAP_HELVETICA_18):
    """Render text at screen coordinates"""
    glColor3f(1.0, 1.0, 1.0)
    glMatrixMode(GL_PROJECTION)
    glPushMatrix()
    glLoadIdentity()
    gluOrtho2D(0, 1000, 0, 800)

    glMatrixMode(GL_MODELVIEW)
    glPushMatrix()
    glLoadIdentity()

    glRasterPos2f(screen_x, screen_y)
    for char in message:
        glutBitmapCharacter(font, ord(char))

    glPopMatrix()
    glMatrixMode(GL_PROJECTION)
    glPopMatrix()
    glMatrixMode(GL_MODELVIEW)


def create_floor_grid():
    """Draw checkered floor pattern"""
    for row in range(WORLD_SIZE):
        for col in range(WORLD_SIZE):
            tile_color = COLOR_PINK if (row + col) % 2 == 0 else COLOR_GREEN
            glColor3f(*tile_color)
            glBegin(GL_QUADS)
            glVertex3f(row * TILE_SIZE, 0, col * TILE_SIZE)
            glVertex3f((row + 1) * TILE_SIZE, 0, col * TILE_SIZE)
            glVertex3f((row + 1) * TILE_SIZE, 0, (col + 1) * TILE_SIZE)
            glVertex3f(row * TILE_SIZE, 0, (col + 1) * TILE_SIZE)
            glEnd()


def construct_boundary_walls():
    """Create four colored walls around the arena"""
    wall_height = 1.0
    wall_depth = 0.2
    arena_size = WORLD_SIZE * TILE_SIZE

    # Wall configurations: (color, position, scale)
    walls = [
        ((0.0, 0.0, 1.0), (arena_size / 2, wall_height / 2, wall_depth / 2),
         (arena_size, wall_height, wall_depth)),  # Blue bottom
        ((0.0, 1.0, 0.0), (arena_size / 2, wall_height / 2, arena_size - wall_depth / 2),
         (arena_size, wall_height, wall_depth)),  # Green top
        ((0.0, 1.0, 1.0), (wall_depth / 2, wall_height / 2, arena_size / 2),
         (wall_depth, wall_height, arena_size)),  # Cyan left
        ((1.0, 0.0, 1.0), (arena_size - wall_depth / 2, wall_height / 2, arena_size / 2),
         (wall_depth, wall_height, arena_size))   # Magenta right
    ]

    for color, pos, scale in walls:
        glColor3f(*color)
        glPushMatrix()
        glTranslatef(*pos)
        glScalef(*scale)
        glutSolidCube(1)
        glPopMatrix()


def build_player_character():
    """Construct player with gun"""
    glPushMatrix()
    glTranslatef(gun_pos_x, 0, gun_pos_z)
    glRotatef(gun_rotation, 0, 1, 0)
    glScalef(0.9, 0.9, 0.9)

    if not is_game_active:
        glRotatef(90, 1, 0, 0)  # Lie down when dead

    # Build legs (cylinders)
    glColor3f(0.0, 0.0, 1.0)
    for leg_offset in [-0.2, 0.2]:
        glPushMatrix()
        glTranslatef(leg_offset, 0.4, 0)
        glRotatef(-90, 1, 0, 0)
        leg_quad = gluNewQuadric()
        gluCylinder(leg_quad, 0.1, 0.05, 0.4, 20, 20)
        gluDeleteQuadric(leg_quad)
        glPopMatrix()

    # Build torso (cuboid)
    glColor3f(0.8, 0.4, 0.0)
    glPushMatrix()
    glTranslatef(0, 1.0, 0)
    glScalef(0.4, 0.6, 0.2)
    glutSolidCube(1)
    glPopMatrix()

    # Build arms (cylinders)
    glColor3f(0.96, 0.8, 0.69)
    for arm_offset in [-0.15, 0.15]:
        glPushMatrix()
        glTranslatef(arm_offset, 1.2, 0.1)
        arm_quad = gluNewQuadric()
        gluCylinder(arm_quad, 0.1, 0.05, 0.4, 20, 20)
        gluDeleteQuadric(arm_quad)
        glPopMatrix()

    # Build gun (cone-shaped cylinder)
    glColor3f(0.5, 0.5, 0.5)
    glPushMatrix()
    glTranslatef(0, 1.2, 0.1)
    gun_quad = gluNewQuadric()
    gluCylinder(gun_quad, 0.08, 0.0, 0.8, 20, 20)
    gluDeleteQuadric(gun_quad)
    glPopMatrix()

    # Build head (sphere)
    glColor3f(0.0, 0.0, 0.0)
    glPushMatrix()
    glTranslatef(0, 1.65, 0)
    glutSolidSphere(0.2, 20, 20)
    glPopMatrix()

    glPopMatrix()


def render_projectiles():
    """Draw all active bullets"""
    glColor3f(1.0, 0.0, 0.0)
    for proj in projectile_list:
        glPushMatrix()
        glTranslatef(proj['px'], 1.2, proj['pz'])
        glScalef(0.15, 0.15, 0.15)
        glutSolidCube(1)
        glPopMatrix()


def render_enemies():
    """Draw all enemies with animation"""
    for foe in enemy_list:
        glPushMatrix()
        glTranslatef(foe['ex'], 0.4, foe['ez'])
        glScalef(foe['size'], foe['size'], foe['size'])

        # Enemy head (red sphere)
        glColor3f(1.0, 0.0, 0.0)
        glPushMatrix()
        glTranslatef(0, 0.2, 0)
        glutSolidSphere(0.2, 20, 20)
        glPopMatrix()

        # Enemy body (black sphere)
        glColor3f(0.0, 0.0, 0.0)
        glPushMatrix()
        glTranslatef(0, 0.45, 0)
        glutSolidSphere(0.12, 20, 20)
        glPopMatrix()

        glPopMatrix()


def advance_projectiles():
    """Update bullet positions and check collisions"""
    global projectile_list, shots_missed_count, total_score, enemy_list

    active_projectiles = []

    # Auto-fire in cheat mode
    if auto_fire_enabled:
        execute_cheat_behavior()

    for proj in projectile_list:
        angle_rad = math.radians(proj['direction'])
        proj['px'] += PROJECTILE_VELOCITY * math.sin(angle_rad)
        proj['pz'] += PROJECTILE_VELOCITY * math.cos(angle_rad)

        # Check if bullet is within bounds
        if 0 <= proj['px'] <= WORLD_SIZE and 0 <= proj['pz'] <= WORLD_SIZE:
            collision_detected = False

            # Check collision with enemies
            for foe in enemy_list[:]:
                dist_x = proj['px'] - foe['ex']
                dist_z = proj['pz'] - foe['ez']
                distance = math.sqrt(dist_x * dist_x + dist_z * dist_z)

                if distance < 0.5:
                    total_score += 10
                    enemy_list.remove(foe)
                    collision_detected = True
                    break

            if not collision_detected:
                active_projectiles.append(proj)
        else:
            # Bullet went out of bounds
            if not auto_fire_enabled:
                shots_missed_count += 1
                print(f"Missed shot! Total missed: {shots_missed_count}")

    projectile_list = active_projectiles


def execute_cheat_behavior():
    """Auto-rotate and fire at enemies in cheat mode - only when enemy is in line of sight"""
    global gun_rotation, current_target_index, projectile_list, fire_cooldown_timer

    # Rotation speed increases with score (same as enemy speed progression)
    base_rotation = 0.5
    rotation_multiplier = 1 + (total_score // 100) * 0.3
    rotation_speed = base_rotation * rotation_multiplier
    gun_rotation = (gun_rotation + rotation_speed) % 360

    if fire_cooldown_timer > 0:
        fire_cooldown_timer -= 1

    # Only fire when gun is PRECISELY pointing at an enemy
    if fire_cooldown_timer == 0 and len(enemy_list) > 0:
        # Check each enemy to see if gun is pointing at it
        for enemy in enemy_list:
            delta_x = enemy['ex'] - gun_pos_x
            delta_z = enemy['ez'] - gun_pos_z
            enemy_angle = math.degrees(math.atan2(delta_x, delta_z))

            # Normalize angles to 0-360 range
            enemy_angle = enemy_angle % 360
            current_gun_angle = gun_rotation % 360

            # Calculate angle difference (accounting for wraparound)
            angle_diff = abs(enemy_angle - current_gun_angle)
            if angle_diff > 180:
                angle_diff = 360 - angle_diff

            # Fire only if PRECISELY pointing at enemy (3 degree tolerance)
            if angle_diff < 3:
                projectile_list.append({
                    'px': gun_pos_x,
                    'pz': gun_pos_z,
                    'direction': gun_rotation
                })
                fire_cooldown_timer = 20  # Faster cooldown for better response
                break  # Fire at one enemy at a time


def animate_enemy_movement():
    """Move enemies toward player and check collisions"""
    global remaining_health, enemy_list, is_game_active

    # Calculate enemy speed based on score (increases every 100 points)
    base_speed = 0.0005
    speed_multiplier = 1 + (total_score // 100) * 0.3
    enemy_speed = base_speed * speed_multiplier

    for foe in enemy_list[:]:
        # Move toward player
        delta_x = gun_pos_x - foe['ex']
        delta_z = gun_pos_z - foe['ez']
        dist = math.hypot(delta_x, delta_z)

        if dist > 0:
            foe['ex'] += enemy_speed * delta_x / dist
            foe['ez'] += enemy_speed * delta_z / dist

        # Animate size (shrink/expand)
        if foe['shrink']:
            foe['size'] -= 0.002
            if foe['size'] <= 0.6:
                foe['shrink'] = False
        else:
            foe['size'] += 0.002
            if foe['size'] >= 1.2:
                foe['shrink'] = True

        # Check collision with player
        collision_dist = math.sqrt(delta_x**2 + delta_z**2)
        if collision_dist < 0.5:
            if remaining_health > 0:
                remaining_health -= 1
                print(f"Hit! Health remaining: {remaining_health}")
            enemy_list.remove(foe)

    # Maintain enemy count
    while len(enemy_list) < ENEMY_COUNT:
        enemy_list.append(generate_new_enemy())

    verify_game_status()


def generate_new_enemy():
    """Spawn enemy at random safe location"""
    while True:
        spawn_x = random.uniform(1, WORLD_SIZE - 1)
        spawn_z = random.uniform(1, WORLD_SIZE - 1)
        if abs(spawn_x - gun_pos_x) > 3 and abs(spawn_z - gun_pos_z) > 3:
            return {'ex': spawn_x, 'ez': spawn_z, 'size': 1.0, 'shrink': True}


def verify_game_status():
    """Check if game over conditions are met"""
    global is_game_active
    if remaining_health <= 0 or shots_missed_count >= 10:
        is_game_active = False


def reset_game_state():
    """Restart the game"""
    global total_score, remaining_health, shots_missed_count, is_game_active
    global projectile_list, gun_pos_x, gun_pos_z, gun_rotation, perspective_mode
    global auto_fire_enabled, auto_aim_camera, fire_cooldown_timer, current_target_index

    total_score = 0
    remaining_health = 5
    shots_missed_count = 0
    is_game_active = True
    gun_pos_x = WORLD_SIZE / 2.0
    gun_pos_z = WORLD_SIZE / 2.0
    gun_rotation = 0.0
    perspective_mode = "third"
    auto_fire_enabled = False
    auto_aim_camera = False
    fire_cooldown_timer = 0
    current_target_index = 0
    projectile_list.clear()
    initialize_enemies()
    print("Game restarted! Score: 0, Lives: 5, Missed: 0")


def initialize_enemies():
    """Create initial enemy set"""
    global enemy_list
    enemy_list = []
    for _ in range(ENEMY_COUNT):
        while True:
            spawn_x = random.uniform(1, WORLD_SIZE - 1)
            spawn_z = random.uniform(1, WORLD_SIZE - 1)
            if abs(spawn_x - gun_pos_x) > 2 and abs(spawn_z - gun_pos_z) > 2:
                enemy_list.append({'ex': spawn_x, 'ez': spawn_z, 'size': 1.0, 'shrink': True})
                break


def configure_camera_view():
    """Set up camera perspective"""
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    gluPerspective(45, 1.25, 1, 100)
    glMatrixMode(GL_MODELVIEW)
    glLoadIdentity()

    if perspective_mode == "third":
        # Third-person camera - rotates around the arena
        cam_x = WORLD_SIZE / 2 + view_distance * math.sin(math.radians(view_angle))
        cam_z = WORLD_SIZE / 2 + view_distance * math.cos(math.radians(view_angle))
        gluLookAt(cam_x, view_elevation, cam_z, WORLD_SIZE / 2, 0, WORLD_SIZE / 2, 0, 1, 0)
    elif perspective_mode == "first":
        # First-person camera - follows gun direction
        if auto_aim_camera and auto_fire_enabled and len(enemy_list) > 0:
            # In cheat mode with V pressed, camera follows target
            target = enemy_list[current_target_index % len(enemy_list)]
            look_x = target['ex']
            look_z = target['ez']
            gluLookAt(gun_pos_x, 1, gun_pos_z, look_x, 1, look_z, 0, 1, 0)
        else:
            # Normal first-person view
            angle_rad = math.radians(gun_rotation)
            look_x = gun_pos_x + math.sin(angle_rad)
            look_z = gun_pos_z + math.cos(angle_rad)
            gluLookAt(gun_pos_x, 1, gun_pos_z, look_x, 1, look_z, 0, 1, 0)


def render_scene():
    """Main display function"""
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    glLoadIdentity()
    glViewport(0, 0, 1000, 800)

    configure_camera_view()

    create_floor_grid()
    construct_boundary_walls()
    build_player_character()
    render_projectiles()
    render_enemies()

    if is_game_active:
        advance_projectiles()
        animate_enemy_movement()

    glDisable(GL_LIGHTING)

    # Display UI text
    if not is_game_active:
        glColor3f(1, 0, 0)
        render_text_overlay(10, 770, f"GAME OVER. Your Score is {total_score}", GLUT_BITMAP_TIMES_ROMAN_24)
        render_text_overlay(10, 750, "Press 'R' to Restart the Game", GLUT_BITMAP_TIMES_ROMAN_24)
    else:
        glColor3f(1, 1, 1)
        render_text_overlay(10, 770, f"Game Score: {total_score}", GLUT_BITMAP_TIMES_ROMAN_24)
        render_text_overlay(10, 750, f"Player life remaining: {remaining_health}", GLUT_BITMAP_TIMES_ROMAN_24)
        render_text_overlay(10, 730, f"Player Bullet Missed: {shots_missed_count}", GLUT_BITMAP_TIMES_ROMAN_24)

    glutSwapBuffers()
    glutPostRedisplay()


def handle_keyboard(key, x, y):
    """Handle WASD movement and cheat toggles"""
    global gun_pos_x, gun_pos_z, gun_rotation, is_game_active, auto_fire_enabled, auto_aim_camera

    if not is_game_active:
        if key == b'r':
            reset_game_state()
        return

    if key == b'c':
        auto_fire_enabled = not auto_fire_enabled
        if auto_fire_enabled:
            print("Cheat mode ACTIVATED - Auto-firing at enemies in line of sight!")
        else:
            print("Cheat mode DEACTIVATED")
        return

    if key == b'v':
        if auto_fire_enabled:
            auto_aim_camera = not auto_aim_camera
            if auto_aim_camera:
                print("Auto-aim camera ENABLED - Camera will track targets in first-person mode")
            else:
                print("Auto-aim camera DISABLED")
        return

    move_step = 0.2
    rotate_step = 5

    if key == b'w':
        # Move forward
        angle_rad = math.radians(gun_rotation)
        gun_pos_x += move_step * math.sin(angle_rad)
        gun_pos_z += move_step * math.cos(angle_rad)
    elif key == b's':
        # Move backward
        angle_rad = math.radians(gun_rotation)
        gun_pos_x -= move_step * math.sin(angle_rad)
        gun_pos_z -= move_step * math.cos(angle_rad)
    elif key == b'a':
        # Rotate left
        gun_rotation = (gun_rotation - rotate_step) % 360
    elif key == b'd':
        # Rotate right
        gun_rotation = (gun_rotation + rotate_step) % 360

    # Keep player within bounds
    boundary_min = 0.5
    boundary_max = WORLD_SIZE - 0.5
    gun_pos_x = max(min(gun_pos_x, boundary_max), boundary_min)
    gun_pos_z = max(min(gun_pos_z, boundary_max), boundary_min)

    glutPostRedisplay()


def handle_special_keys(key, x, y):
    """Handle arrow key camera controls"""
    global view_angle, view_distance, view_elevation, is_game_active

    if not is_game_active:
        return

    if key == GLUT_KEY_LEFT:
        # Rotate camera left (counter-clockwise around arena)
        view_angle = (view_angle - 5) % 360
    elif key == GLUT_KEY_RIGHT:
        # Rotate camera right (clockwise around arena)
        view_angle = (view_angle + 5) % 360
    elif key == GLUT_KEY_UP:
        # Move camera closer and lower (more side/front view)
        view_distance = max(view_distance - 1, 5)
        view_elevation = max(view_elevation - 1, 2)
    elif key == GLUT_KEY_DOWN:
        # Move camera farther and higher (more top-down view)
        view_distance = min(view_distance + 1, 30)
        view_elevation = min(view_elevation + 1, 25)

    glutPostRedisplay()


def handle_mouse(button, state, x, y):
    """Handle mouse clicks for shooting and camera toggle"""
    global perspective_mode, is_game_active

    if not is_game_active:
        return

    if button == GLUT_LEFT_BUTTON and state == GLUT_DOWN:
        print("Bullet fired!")
        projectile_list.append({
            'px': gun_pos_x,
            'pz': gun_pos_z,
            'direction': gun_rotation
        })
    elif button == GLUT_RIGHT_BUTTON and state == GLUT_DOWN:
        perspective_mode = "first" if perspective_mode == "third" else "third"


def initialize_opengl():
    """Initialize OpenGL settings"""
    glClearColor(0.0, 0.0, 0.0, 1.0)
    glEnable(GL_DEPTH_TEST)


def reshape_window(width, height):
    """Handle window reshape"""
    glViewport(0, 0, width, height)
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    gluPerspective(45, width / height, 1, 100)
    glMatrixMode(GL_MODELVIEW)


def idle_function():
    """Idle callback for continuous updates"""
    glutPostRedisplay()


def main():
    """Initialize and run the game"""
    glutInit()
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH)
    glutInitWindowSize(1000, 800)
    glutCreateWindow(b"Bullet Frenzy")

    initialize_opengl()
    initialize_enemies()

    glutDisplayFunc(render_scene)
    glutReshapeFunc(reshape_window)
    glutKeyboardFunc(handle_keyboard)
    glutSpecialFunc(handle_special_keys)
    glutMouseFunc(handle_mouse)
    glutIdleFunc(idle_function)

    glutMainLoop()


if __name__ == "__main__":
    main()